swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

paths:
  /v1/order:
    get:
      operationId: "api.controller.v1.order.get"
      parameters:
        - name: customer_name
          description: customer name who is placing the order
          in: query
          type: string
          required: true

        - name: customer_email
          description: customer email who is placing the order
          in: query
          type: string
          required: false

      responses:
        200:
          description: "Customer order details fetched"

    post:
      operationId: "api.controller.v1.order.post"
      parameters:
        - name: order_data
          in: body
          schema:
            $ref: '#/definitions/Order'
      responses:
        200:
          description: "Successfully added order"

definitions:
  Order:
    type: object
    required:
      - customer_name
      - customer_email
      - comment_data
    properties:
      customer_name:
        type: string
        description: customer name
        example: "ankur"
        minLength: 1
        maxLength: 100
      customer_email:
        type: string
        description: customer_email
        example: "a@abc.com"
        minLength: 1
        maxLength: 100
      comment_data:
        type: array
        description: array
        example: [{"foo": "bar"}]
        items:
          type: object
          required:
            - foo
          properties:
            foo:
              type: string
              description: foo
