swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

paths:
  /v1/order:
    get:
      operationId: "api.controller.v1.order.get"
      responses:
        200:
          description: "Customer order details fetched"

    post:
      operationId: "api.controller.v1.order.post"
      responses:
        200:
          description: "Successfully added order"
