"""empty message

Revision ID: 005f038e32df
Revises: 3a6c9b01d453
Create Date: 2018-09-08 23:52:38.160750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005f038e32df'
down_revision = '3a6c9b01d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
