"""empty message

Revision ID: 028d382a14b8
Revises: a82da8550020
Create Date: 2018-09-08 17:32:09.023460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028d382a14b8'
down_revision = 'a82da8550020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('customer_emails', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'customer_emails')
    # ### end Alembic commands ###
