"""empty message

Revision ID: 943b943147f3
Revises: 028d382a14b8
Create Date: 2018-09-08 17:33:01.260599

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '943b943147f3'
down_revision = '028d382a14b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'customer_emails')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('customer_emails', mysql.VARCHAR(length=120), nullable=False))
    # ### end Alembic commands ###
