"""empty message

Revision ID: d6396ebe8dc7
Revises: 005f038e32df
Create Date: 2018-09-08 23:59:55.302646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6396ebe8dc7'
down_revision = '005f038e32df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('text', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'text')
    # ### end Alembic commands ###
