apiVersion: apps/v1
kind: Deployment
metadata:
  name: red-deployment
  labels:
    app: red
spec:
  replicas: 2
  selector:
    matchLabels:
      app: red
  template:
    metadata:
      labels:
        app: red
    spec:
      containers:
        - name: red
          image: ankurj630/hello-flask
          env:
            - name: "color"
              value: "red"
            - name: "up"
              value: "http://green"
          ports:
            - containerPort: 5000
