apiVersion: v1
kind: Pod
metadata:
  name: green-pod
  labels:
    color: green
spec:
  containers:
    - name: green
      image: ankurj630/hello-flask
      env:
        - name: "color"
          value: "green"
      ports:
        - containerPort: 5000
