image: alpine:latest

stages:
  - build

# staging-migration:
#   stage: migration
#   image: docker:stable-git
#   services:
#   - docker:stable-dind
#   variables:
#     DOCKER_DRIVER: overlay2
#     DB_USER_NAME: root@admin$12
#   script:
#     - apk add --no-cache python3
#     - python3 -m ensurepip && rm -r /usr/lib/python*/ensurepip
#     - pip3 install --upgrade pip setuptools
#     - if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi
#     - if [[ ! -e /usr/bin/python ]]; then ln -sf /usr/bin/python3 /usr/bin/python; fi
#     - rm -r /root/.cache
#     - python --version
#     - pip --version
#     - echo $DB_USER_NAME
#   only:
#     - staging

staging-build:
  stage: build
  image: docker:stable-git
  services:
  - docker:stable-dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - echo $GITLAB_USERNAME
    - echo $GITLAB_PASSWORD
    - echo "$GITLAB_PASSWORD" | docker login registry.gitlab.com -u $GITLAB_USERNAME --password-stdin
    - docker build -t registry.gitlab.com/$GITLAB_USERNAME/docker-flask:staging .
    - docker push registry.gitlab.com/$GITLAB_USERNAME/docker-flask
  environment:
    name: staging
  only:
    - staging
