apiVersion: v1
kind: Pod
metadata:
  name: red-pod
  labels:
    app: red
spec:
  containers:
    - name: red
      image: ankurj630/hello-flask
      env:
        - name: "color"
          value: "red"
      ports:
        - containerPort: 5000
