apiVersion: v1
kind: Service
metadata:
  name: green
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  g_mapping
      prefix: /sg/
      service: green
spec:
  selector:
    color: green
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
